#Nombre del workflow
name: Pruebas E2E en Cypress
#Condiciones del workflow
on:
  push:
    branches: [main]
jobs:
   ejecute_cypress:
     runs-on: ubuntu-latest
     steps:
       - name: Bajar el código
         uses: actions/checkout@v2

       - name: Instalar Node.js
         uses: actions/setup-node@v4
         with:
           node-version: '20'

       - name: Instalar dependencias
         run: npm ci

       - name: Ejecutar Cypress
         uses: cypress-io/github-action@v6
         with:
           build: npm run build
           start: npm run preview